export const PostActionTypes = {
	GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
	GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',
	GET_POST_BY_SLUG_SUCCESS: 'GET_POST_BY_SLUG_SUCCESS',
	GET_POST_BY_SLUG_FAILURE: 'GET_POST_BY_SLUG_FAILURE',
	GET_POSTS_BY_TAG_SUCCESS: 'GET_POSTS_BY_TAG_SUCCESS',
	GET_POSTS_BY_TAG_FAILURE: 'GET_POSTS_BY_TAG_FAILURE',
}